### ISSUE TITLE
FATAL: Test CUDA failure util.cu:555 'CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by krishnakantsingh14** [krishnakantsingh14/esd-apptainer#33]
During a performance test of the nccl-cuda-arbor-openmpi container on the local HPC cluster, the NCCL all-reduce test failed to initialize due to a CUDA version mismatch between the container runtime and the host driver.

Environment Metadata:
    **Host**: lrdn3205
    **Host CUDA Driver Version**: Cuda/12.2 
    **Container Image**: oras://docker-registry.ebrains.eu/hpc-containers/nccl-cuda-arbor-openmpi:v1.0
    **Container CUDA Toolkit Version**: 13.1

The container is built with **CUDA 13.1**, but the host driver only supports up to **CUDA 12.2**. Per **NVIDIA’s compatibility requirements**, the host driver must be **equal to or newer** than the toolkit version used to compile the application.

```
singularity pull --no-https nccl-cuda-arbor-openmpi_v1.0.sif oras://docker-registry.ebrains.eu/hpc-containers/nccl-cuda-arbor-openmpi:v1.0

singularity exec --nv  nccl-cuda-arbor-openmpi_v1.0.sif sh -c "nvidia-smi topo -m && /opt/src/nccl-tests/build/all_reduce_perf -b 8 -e 8G -f 2 -g 4"
    GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity    GPU NUMA ID
GPU0     X     NV4    NV4    NV4    PXB    NODE    NODE    NODE    0-15    0        N/A
GPU1    NV4     X     NV4    NV4    NODE    PXB    NODE    NODE    0-15    0        N/A
GPU2    NV4    NV4     X     NV4    NODE    NODE    PXB    NODE    0-15    0        N/A
GPU3    NV4    NV4    NV4     X     NODE    NODE    NODE    PXB    0-15    0        N/A
NIC0    PXB    NODE    NODE    NODE     X     NODE    NODE    NODE                
NIC1    NODE    PXB    NODE    NODE    NODE     X     NODE    NODE                
NIC2    NODE    NODE    PXB    NODE    NODE    NODE     X     NODE                
NIC3    NODE    NODE    NODE    PXB    NODE    NODE    NODE     X                 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3

[1768483701.951407] [lrdn3205:234882:0]          parser.c:2359 UCX  WARN  unused environment variable: UCX_PATH
[1768483701.951407] [lrdn3205:234882:0]          parser.c:2359 UCX  WARN  (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
# nccl-tests version 2.17.7 nccl-headers=22809 nccl-library=22809
# Collective test starting: all_reduce_perf
# nThread 1 nGpus 4 minBytes 8 maxBytes 8589934592 step: 2(factor) warmup iters: 1 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
lrdn3205: Test CUDA failure util.cu:555 'CUDA driver version is insufficient for CUDA runtime version'
 .. lrdn3205 pid 234882: Test failure common.cu:1188
[ksingh00@lrdn3205 try26_singh]$ slurmstepd: error:  mpi/pmix_v3: _errhandler: lrdn3205 [0]: pmixp_client_v2.c:212: Error handler invoked: status = -25, source = [slurm.pmix.32370971.0:0]
srun: Job step aborted: Waiting up to 182 seconds for job step to finish.
slurmstepd: error: *** STEP 32370971.0 ON lrdn3205 CANCELLED AT 2026-01-15T14:28:23 ***
srun: error: lrdn3205: task 0: Killed

```

**Comment by krishnakantsingh14** [comment]
This issue arise duw to Apptainer has newer version of cuda as compare to the host.
```
**Host CUDA Driver Version: Cuda/12.2**
Container Image: oras://docker-registry.ebrains.eu/hpc-containers/nccl-cuda-arbor-openmpi:v1.0
**Container CUDA Toolkit Version: 13.1** 
```

This is resolved by downgrading the cuda version in apptainer.
